version: "3"
services:
  frontend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - todo_frontend:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: oayanda
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  todo_frontend:
  db:
